### ISSUE TITLE
Error when credentials are wrong

### ISSUE THREAD

**Issue by GuillaumeRx** [noook/igdm-cli#1]
When entered credentials are wrong the CLI throws an unexpected error

```
TypeError: (0 , _fs.rmSync) is not a function
```

error happens at `auth.ts` line `78` because of the the `rmSync` in `logout` function

**Comment by backl1n** [comment]
idem for me

**Comment by noook** [comment]
Gonna check that out.

**Comment by noook** [comment]
Hope [this](160bc3a71b746f24f640a0d89fa4c10d52694d2e) will fix
