### ISSUE TITLE
Pressing enter in a conversation crashes the app

### ISSUE THREAD

**Issue by LukeCageCodes** [noook/igdm-cli#6]
When I'm in a conversation thread, and I press enter (without having entered text), the app crashes.

I propose that enter is caught and goes back to the conversations list. This would enable going back and forther between the message thread and the conversation list without typing \l.

**Comment by mihilt** [comment]
i think u can edit it ur self with easy way
just clone this app and add `case '':` to line 97 line in `direct-messaging.ts` file promt function
but i think it is better to add it in 98 line
cuz it can help us dont have to use \r anymore

anyway when its done, build this app
find where ur nodeJS global module is installed
change /igdm/dist/index.js file to built file :)
